AWSTemplateFormatVersion: 2010-09-09
Description: ECS cluster launchtype Fargate.
Parameters:
  ECSClusterName:
    Type: String
    Description: >-
      The ECS cluster that runs the write-vito servie
    Default: ecs-cluster
Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      ServiceConnectDefaults:
        Namespace: ecs-cluster
      Tags: []
Outputs:
  ECSCluster:
    Description: The created cluster.
    Value: !Ref ECSCluster
